# Generated by Django 4.1.7 on 2023-03-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('work_experience', models.CharField(max_length=50)),
                ('latest_education_degree', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
